name: CI/CD for Next.js App

on:
  push:
    branches:
      - main  # Trigger on pushes to the `main` branch

jobs:
  build-and-deploy:
    environment: EC2
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js for building the app
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the Node.js version compatible with your project

    # Step 3: Set up Docker for building and pushing the image
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Set this in your GitHub repository secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t naufaladrna08/app-next-test:latest .

    - name: Push Docker Image to DockerHub
      run: docker push naufaladrna08/app-next-test:latest

    # Step 4: Deploy to VPS
    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Add your private key to GitHub Secrets
        VPS_HOST: ${{ secrets.VPS_HOST }}               # Add your VPS IP/Hostname to GitHub Secrets
        VPS_USER: ${{ secrets.VPS_USER }}               # Add your VPS username to GitHub Secrets
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key
        bash -c "ssh -t -i ssh_key $VPS_USER@$VPS_HOST \
          \"docker pull naufaladrna08/app-next-test:latest && \
          docker stop app-next-test || true && \
          docker rm app-next-test || true && \
          docker run -d --name app-next-test -p 80:3000 --restart always naufaladrna08/app-next-test:latest && \
          docker image prune -f\""