name: CI/CD for Next.js App

on:
  push:
    branches:
      - main  # Trigger on pushes to the `main` branch

jobs:
  build-and-deploy:
    environment: EC2
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js for building the app
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the Node.js version compatible with your project

    # Step 3: Set up Docker for building and pushing the image
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Set this in your GitHub repository secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t naufaladrna08/app-next-test:latest .

    - name: Push Docker Image to DockerHub
      run: docker push naufaladrna08/app-next-test:latest

    # Step 4: Deploy to VPS
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker pull naufaladrna08/app-next-test:latest
          docker stop app-next-test
          docker rm app-next-test
          docker run -d --name app-next-test -p 80:3000 --restart always naufaladrna08/app-next-test:latest
          docker image prune -f